defaults: &defaults
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 10
  username: postgres

development:
  <<: *defaults
  database: practice

# test:
#   <<: *defaults
#   database: practice
#
# staging:
#   <<: *defaults
#   database: practice
#   password:
#
# production:
#   <<: *defaults
#   database: practice
#   password:
